export const ADMIN_PANEL_CATEGORY_CHANGE = 'ADMIN_PANEL_CATEGORY_CHANGE'

export const GET_ADMIN_PANEL_DATA_REQUEST = 'GET_ADMIN_PANEL_DATA_REQUEST'
export const GET_ADMIN_PANEL_DATA_SUCCESS = 'GET_ADMIN_PANEL_DATA_SUCCESS'
export const GET_ADMIN_PANEL_DATA_FAILURE = 'GET_ADMIN_PANEL_DATA_FAILURE'

export const UPDATE_ADMIN_PANEL_DATA_REQUEST = 'UPDATE_ADMIN_PANEL_DATA_REQUEST'
export const UPDATE_ADMIN_PANEL_DATA_SUCCESS = 'UPDATE_ADMIN_PANEL_DATA_SUCCESS'
export const UPDATE_ADMIN_PANEL_DATA_FAILURE = 'UPDATE_ADMIN_PANEL_DATA_FAILURE'

export const DELETE_IMAGE_DATA_REQUEST = 'DELETE_IMAGE_DATA_REQUEST'
export const DELETE_IMAGE_DATA_SUCCESS = 'DELETE_IMAGE_DATA_SUCCESS'
export const DELETE_IMAGE_DATA_FAILURE = 'DELETE_IMAGE_DATA_FAILURE'

export const ADD_NEW_IMAGE_REQUEST = 'ADD_NEW_IMAGE_REQUEST'
export const ADD_NEW_IMAGE_SUCCESS = 'ADD_NEW_IMAGE_SUCCESS'
export const ADD_NEW_IMAGE_FAILURE = 'ADD_NEW_IMAGE_FAILURE'

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_ERROR = "SIGN_IN_ERROR"
export const FORCE_SIGN_OUT = "FORCE_SIGN_OUT"

export const ADD_UPDATE_FORM_DATA = "ADD_UPDATE_FORM_DATA"
export const RESET_FORM = "RESET_FORM"